### ISSUE TITLE
Closing local computer lid stops remote play

### ISSUE THREAD

**Issue by smoltron** [kpcyrd/spotify-launcher#16]
This is possibly an Arch or Spotify problem. I cannot identify who to blame.
When I close my laptop lid, remote spotify connect server stops playing. This is not a good behaviour. Remote play should be independent from local computer behaviour. Is there a solution?

**Comment by kpcyrd** [comment]
The launcher is only downloading and extracting the package, I can't provide support for any issues beyond this unfortunately.
