### ISSUE TITLE
"Enhance" large playlists makes them unavailable

### ISSUE THREAD

**Issue by BjarneBetjent** [kpcyrd/spotify-launcher#19]
I have a large playlist with 1500 songs. 
When using the enhance option for this playlist, I'm unable to access it. It'll try to render the songs, but will quickly black out the client and show a "reload the page" option. This also removes the option to opt out of enhance to temporarily fix the problem.

**Comment by kpcyrd** [comment]
The launcher is only downloading and extracting the package, I can't provide support for any issues beyond this unfortunately.
