### ISSUE TITLE
Adding image to README

### ISSUE THREAD

**Issue by TornaxO7** [kpcyrd/spotify-launcher#21]
hello! It would be nice if you could add an image of `spotify-launcher` so others could see the interface and how to interact with it before downloading it :)

**Comment by kpcyrd** [comment]
there's barely anything, there's a basic progress bar during the download and some logging if you run it from a terminal but that's it :smiley_cat:

**Comment by TornaxO7** [comment]
Aye, you're right. I just installed it and I'm quite happy with it :) Thank you!
