### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by istipisti113** [kpcyrd/spotify-launcher#22]
When I try to open it from the terminal by "sudo spotify-launcher" it opens a blank window and in the terminal it spams "Authorization required but no protocol specified". I don't know what I might have done wrong, please help!

**Comment by vimpostor** [comment]
> sudo spotify-launcher

You shouldn't run it as root. Just start it as normal user, and it should work.

**Comment by kpcyrd** [comment]
Closing since it's expected to run as your normal desktop user instead of sudo (as already pointed out)
