### ISSUE TITLE
Keyboard shortcuts doesn't work?

### ISSUE THREAD

**Issue by ludverse** [kpcyrd/spotify-launcher#26]
I'm not sure I might have configured something wrong but I cant get keyboard shortcuts to work like the official Spotify packages, at least for Windows where I come from, e.g `Ctrl+Right` for next track, or `Ctrl+Up` for increase volume. Is this a known bug?

**Comment by kpcyrd** [comment]
spotify-launcher is only a client to download and install the spotify apt package on systems that aren't apt based, if everything is starting correctly but keyboard shortcuts are missing there's likely nothing i can do about this.

You could try if it's working correctly on debian/ubuntu and then attempt to figure out what's different on your system and why it's not working.
