### ISSUE TITLE
Error stop downloading spotify app

### ISSUE THREAD

**Issue by gotha-homester** [kpcyrd/spotify-launcher#3]
Hello,

While spotify-launcher is downloading the spotify app, it stop itself

`[2022-06-14T16:36:05Z INFO  spotify_launcher::apt] Downloading deb file for "spotify-client_1.1.84.716.gc5f8b819_amd64.deb" version="spotify-client" ("1:1.1.84.716.gc5f8b819")`
`[2022-06-14T16:36:05Z DEBUG spotify_launcher::http] Downloading "http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.84.716.gc5f8b819_amd64.deb"...`
` This option is not available. Please see --help for all possible usages.`
`Error: Broken pipe (os error 32)`

Idk what happend, i use arch

btw, nice project

**Comment by kpcyrd** [comment]
mhm, the error message is coming from the zenity binary that's being used as a progress indicator for the download:

```
% strings /usr/bin/zenity | rg 'This option is not available'
This option is not available. Please see --help for all possible usages.
%
```

Can you try if this works on your machine?
```sh
for x in `seq 0 10 100`; do echo $x; sleep 0.3; done | zenity --progress --title "Downloading spotify" --text="Downloading..." --no-cancel --ok-label "😺"
```

**Comment by gotha-homester** [comment]
ohh,its my problem, the $LANG is not set,it still default,i forgot set the $LANG while i installation,thanks for response :D
