### ISSUE TITLE
Spotify Launcher takes ~1 minute and 40 seconds to launch on Wayland backend

### ISSUE THREAD

**Issue by AniAggarwal** [kpcyrd/spotify-launcher#30]
When using the following arguments, both when supplied through the config file or using command line arguments results in a wait of about 1:40 to open the app. 
`extra_arguments = ["--enable-features=UseOzonePlatform", "--ozone-platform=wayland"]`

Below is the output when running the launcher:
```shell
❯ spotify-launcher              
[2023-08-28T21:32:48Z INFO  spotify_launcher::config] Loading configuration file at "/home/ani/.config/spotify-launcher.conf"
[2023-08-28T21:32:48Z INFO  spotify_launcher] No update needed
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
/home/ani/.local/share/spotify-launcher/install/usr/share/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /home/ani/.local/share/spotify-launcher/install/usr/share/spotify/spotify)
/home/ani/.local/share/spotify-launcher/install/usr/share/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /home/ani/.local/share/spotify-launcher/install/usr/share/spotify/spotify)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
```

When launching without any arguments or when lauching only with `"--enable-features=UseOzonePlatform"` the app opens instantly.

System info:
Arch Linux, 6.1.47-1-lts
On Hyprland, lauched via Zsh and Kitty

Let me know if any other information is needed.

**Comment by kpcyrd** [comment]
Thanks for documenting this, but I recommend to only configure additional arguments if absolutely necessary and running the app with default arguments seems to be working correctly for you.

**Comment by AniAggarwal** [comment]
Unfortunately running without any parameters means that the launch is immediate but the text is blurry on my HiDPI display (set to 2x scale).
Using the force scale factor doesn't help as I have my laptop plugged into a monitor which runs at native 1x scale and this leads to weird behavior.

The blurry/pixelated text is not present when on Wayland backend.
