### ISSUE TITLE
Arch Linux missing dependecy

### ISSUE THREAD

**Issue by knedl1k** [kpcyrd/spotify-launcher#33]
After the last update, I was unable to run the application on Arch Linux. After further investigation, I found that there is probably a new dependency missing in the [pacman repository](https://archlinux.org/packages/extra/x86_64/spotify-launcher/).

Terminal output when I tried to launch the application:
```
~ ❯ spotify-launcher
[2023-09-09T10:14:24Z INFO spotify_launcher::config] Loading configuration file at "/etc/spotify-launcher.conf"
[2023-09-09T10:14:24Z INFO spotify_launcher] No update needed
spotify: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
```

I fixed it with [libayatana-appindicator](https://archlinux.org/packages/extra/x86_64/libayatana-appindicator/ ) package. After installing it, everything works.

**Comment by kpcyrd** [comment]
There was an update yesterday (spotify-launcher 0.5.1-2) and libayata-appindicator is currently listed as a dependency (not your fault, your mirror might be out of date):

![image](https://github.com/kpcyrd/spotify-launcher/assets/7763184/c4a689f6-3354-4079-8505-c1ed3a93be20)

See #32
