### ISSUE TITLE
Update fails: "Failed to find data entry in .deb"

### ISSUE THREAD

**Issue by NicoRumm** [kpcyrd/spotify-launcher#52]
The update to spotify-client_1.2.47.364.gf06e5cee_amd64.deb ([link](http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.2.47.364.gf06e5cee_amd64.deb)) fails, because there is no "data.tar.gz" in the .deb file. 

Instead there is "data.tar.xz" and this isn't handled by the [code](https://github.com/kpcyrd/spotify-launcher/blob/3b7ca9cc624829ed1f6bfa91516469d522d9d37f/src/extract.rs#L60).

**Comment by XLThinOreos1** [comment]
I am having the same problem and I'm glad I am not the only one.

**Comment by ih8d8** [comment]
I'm having the same issue.

**Comment by jcul** [comment]
Same issue here, as a workaround for now, you can skip the update.

```
spotify-launcher --skip-update
```

Launches fine for me on the old version.

**Comment by jcul** [comment]
I created a pull request to just decompress the xz.
Seems to work OK on the latest upstream deb.

https://github.com/kpcyrd/spotify-launcher/pull/53

**Comment by IgorRSGraziano** [comment]
Im having the same issue

**Comment by Salvaju29ro** [comment]
When I try to open it it continues to download, I click on the icon again and it downloads again. Is it the same problem?

**Comment by Serpentarius13** [comment]
> When I try to open it it continues to download, I click on the icon again and it downloads again. Is it the same problem?

Yes, you can try using command in terminal or journalctl

**Comment by prstephens** [comment]
> When I try to open it it continues to download, I click on the icon again and it downloads again. Is it the same problem?

yup same here.

**Comment by balejin** [comment]
Currently having the same issue, when running with -v. @jcul method worked

**Comment by eduardhojbota** [comment]
Can confirm.
```sh
  ~ spotify-launcher                                                                                                                               09:50:26
[2024-09-26T06:50:44Z INFO  spotify_launcher::config] Loading configuration file at "/etc/spotify-launcher.conf"
[2024-09-26T06:50:44Z INFO  spotify_launcher::apt] Downloading release file...
[2024-09-26T06:50:45Z INFO  spotify_launcher::apt] Downloading signature...
[2024-09-26T06:50:45Z INFO  spotify_launcher::apt] Verifying pgp signature...
[2024-09-26T06:50:45Z INFO  spotify_launcher::apt] Signature verified successfully!
[2024-09-26T06:50:45Z INFO  spotify_launcher::apt] Downloading package index...
[2024-09-26T06:50:45Z INFO  spotify_launcher::apt] Verifying with sha256sum hash...
[2024-09-26T06:50:45Z INFO  spotify_launcher::apt] Downloading deb file for "spotify-client_1.2.47.364.gf06e5cee_amd64.deb" version="spotify-client" ("1:1.2.47.364.gf06e5cee")
[2024-09-26T06:50:45Z INFO  spotify_launcher::apt] Retrying download...
[2024-09-26T06:50:46Z INFO  spotify_launcher::apt] Verifying with sha256sum hash...
Error: Failed to find data entry in .deb
```

**Comment by Davilarek** [comment]
I would suggest using "👍" if this issue affects you guys, instead of spamming "same issue", as doing that doesn't bring anything new to this conversation

**Comment by robvanderlee** [comment]
This is breaking my client on Linux right now. I'm specifically using the [Snap version](https://snapcraft.io/spotify) to make application links work. As on Linux there is _no other_ way to join jams other than the desktop app.

I've tried manually downloading the client with:

```
# Print the url to the deb package
spotify-launcher --print-deb-url

# Downloaded the package
cd ~/Downloads; wget http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.2.47.364.gf06e5cee_amd64.deb

# Try to load the deb
spotify-launcher --deb=/home/rob/Downloads/spotify-client_1.2.47.364.gf06e5cee_amd64_2.deb
[2024-09-26T08:40:40Z INFO  spotify_launcher::config] Loading configuration file at "/etc/spotify-launcher.conf"
Error: Failed to find data entry in .deb
```

It seems the deb is corrupt so it won't let me install this new version. Without the new version the client will try to update itself or alternativly with `--skip-update` ignore my jam urls alltogether... In addition, I cannot verify my 'corrupted' deb because there are no sums to verify against.

**Comment by kpcyrd** [comment]
Somebody submitted a patch: https://github.com/kpcyrd/spotify-launcher/pull/53

**Comment by ragusa87** [comment]
Regarding the patch, I wonder if it is better to kill the app (bail) if the update failed (as it is today) or just output a warning (on stderr) and launch the non-updated binary ?

**Comment by kpcyrd** [comment]
Probably, that would also help with the cases when the signing key gets rotated.
