### ISSUE TITLE
Pass arguments + flags to `spotify` executable

### ISSUE THREAD

**Issue by tfachmann** [kpcyrd/spotify-launcher#6]
Is it possible to send arguments + flags to the `spotify` executable?

E.g. for wayland support it is necessary to start spotify like this

```
spotify --enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by kpcyrd** [comment]
This is now possible in the 0.3.0 release:

```
$ cat /etc/spotify-launcher.conf 
[spotify]
extra_arguments = ["--enable-features=UseOzonePlatform", "--ozone-platform=wayland"]
```

**Comment by tfachmann** [comment]
Cool, thanks a lot for implementing!!

**Comment by D3SOX** [comment]
Just out of interest: Why do you need these parameters for Spotify on Wayland? I'm also on Wayland (KDE Plasma) and it works without them.

**Comment by tfachmann** [comment]
Is it running natively on wayland, or is there an xwayland session in between?
To test this, you might use the small program called [xeyes](https://gitlab.freedesktop.org/xorg/app/xeyes). If the eyes move when hovering over `spotify`, it runs on xwayland. If they don't move, it is indeed running natively on wayland.

I'm using a minimal compositor ([sway](https://github.com/swaywm/sway)), if it runs natively on KDE, it may be the case that they have special flags / optimizations for apps in the [Chromium Embedded Framework](https://github.com/chromiumembedded/cef) I don't know of.
