### ISSUE TITLE
The cat emoji is gone :(

### ISSUE THREAD

**Issue by portasynthinca3** [kpcyrd/spotify-launcher#64]
Hi! I've been a user of this tool for a while, and I have to say - I'm enjoying it! Thank you for making and maintaining it!

The history of my day getting a little bit better from seeing the smiley cat every time my Spotify client updates dates way way back, and this is the oldest confirmation that I could find:
![cat](https://github.com/user-attachments/assets/ac0d1e08-810e-49d6-9249-9a0226aea4a0)

However, I unfortunately have to announce that the smiley cat emoji in the dialog is gone :(
![nocat](https://github.com/user-attachments/assets/a7e159d1-f161-4f23-8e18-5fb9d100b1d9)

I do not know what caused this, but I would like to know if there's maybe a way to get the cat back? Please?

Again, thank you for making this awesome tool.

**Comment by she11sh0cked** [comment]
This seems to be a problem with either zenity or gtk. The cat emoji is still there:
https://github.com/kpcyrd/spotify-launcher/blob/15b5453b27122e0944b6663a01e8b2ed9509d86e/src/progress.rs#L12-L21
![image](https://github.com/user-attachments/assets/5e703261-51a6-4900-b4ec-602f4e917cfc)

**Comment by she11sh0cked** [comment]
I haven't tested others, but it seems to only be a problem with the `--progress` flag. Maybe file a ticket over at zenity's repo @portasynthinca3? 
![image](https://github.com/user-attachments/assets/3f803731-a96d-4c39-9f64-a97ef73edc52)

**Comment by portasynthinca3** [comment]
Thanks! Done: https://gitlab.gnome.org/GNOME/zenity/-/issues/100

**Comment by portasynthinca3** [comment]
Looks like they fixed the bug in Zenity. Closing this issue here.

**Comment by kpcyrd** [comment]
I saw this issue back then and it made me really happy how me being silly a while back has brightened people's days throughout the years. Thanks for filing this. :sparkles:

I also think it's really cool how a cat emoji and this repo has led to a bugfix in zenity.

Keep being awesome, have a great day meow! 😺
